export const ADD_ITEM = "ADD_ITEM";
export const ADD_INCREASE_ITEM_DETAIL = "ADD_INCREASE_ITEM";
export const CHANGE_INPUT_ITEM = "CHANGE_INPUT_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE_ITEM = "INCREASE_ITEM";
export const DECREASE_ITEM = "DECREASE_ITEM";
export const CLEAR_ITEM = "CLEAR_ITEM";
